# Generated by Django 2.1.1 on 2018-12-11 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField(default='这是一个默认的评论,作者贼懒')),
                ('comment_time', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('好评', 'GOOD'), ('差评', 'BAD')], default='好评', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('img_url', models.CharField(default='https://www.google.com', max_length=240)),
                ('reserve', models.IntegerField(default=9999)),
                ('price', models.FloatField(default=100)),
                ('detail', models.TextField(default='商品描述,商品描述')),
                ('good_rating', models.IntegerField(default=100)),
                ('bad_rating', models.IntegerField(default=0)),
                ('sales_quantity', models.IntegerField(default=500)),
                ('send_address', models.CharField(default='南宁', max_length=240)),
                ('category', models.CharField(choices=[('食物', 'FOOD'), ('书籍', 'BOOK'), ('日用品', 'DAILY'), ('电子产品', 'ELE'), ('杂项', 'OTHER')], default='食物', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('pay', models.BooleanField(default=False)),
                ('total_price', models.FloatField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('pay_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Goods')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_items', to='backend.Order')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('money', models.FloatField(default=1000)),
                ('address', models.CharField(default='广西大学', max_length=240)),
                ('phone_number', models.CharField(default='123456789', max_length=11)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('age', models.FloatField(default=20)),
                ('sex', models.CharField(choices=[('男', '1'), ('女', '2')], default='男', max_length=10)),
                ('career', models.CharField(choices=[('学生', 'S'), ('老师', 'T')], default='学生', max_length=40)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='backend.UserInfo'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='backend.UserInfo'),
        ),
        migrations.AddField(
            model_name='goods',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='backend.UserInfo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backend.Goods'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.UserInfo'),
        ),
    ]
