# Generated by Django 2.1.1 on 2018-12-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181211_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.FloatField(default=5.0),
        ),
    ]
