# Generated by Django 2.1.1 on 2019-06-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_comment_parent_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionsInfo',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=60)),
                ('exception_times', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExceptionsVideo',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=60)),
                ('number_of_people', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True, verbose_name='到来时间')),
                ('video_path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SecurityGuard',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='account',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
