# Generated by Django 2.1.1 on 2019-06-03 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20190602_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceptionsinfo',
            old_name='area',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='exceptionsvideo',
            old_name='area',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='exceptionsvideo',
            old_name='number_of_people',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='securityguard',
            old_name='area',
            new_name='address',
        ),
    ]
