# Generated by Django 2.1.1 on 2019-06-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190603_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoExceptions',
            fields=[
                ('eid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=60, unique=True)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
                ('vid', models.IntegerField()),
                ('time', models.DateTimeField(auto_now=True, verbose_name='到来时间')),
                ('is_deal', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='exceptionsinfo',
            name='address',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='exceptionsinfo',
            name='exception_times',
            field=models.IntegerField(default=1),
        ),
    ]
