# Generated by Django 2.1.1 on 2019-06-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20190604_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoexceptions',
            name='address',
            field=models.CharField(max_length=60),
        ),
    ]
