# Generated by Django 2.1.1 on 2019-06-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20190605_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoexceptions',
            old_name='eid',
            new_name='tid',
        ),
    ]
