# Generated by Django 2.1.1 on 2019-06-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20190606_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='threshold',
            field=models.IntegerField(default=5),
        ),
    ]
