# Generated by Django 2.1.1 on 2019-06-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20190606_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptionsvideo',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='到来时间'),
        ),
        migrations.AlterField(
            model_name='todoexceptions',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='到来时间'),
        ),
    ]
